### ISSUE TITLE
作者您好，请教您几个问题

### ISSUE THREAD

**Issue by SeddonShen** [licaomeng/canvas-zoom#2]
如果我想做室内循迹的话，请问您有什么好的看法或者建议呢？期待您的回复

**Comment by licaomeng** [comment]
這個我之前有做過。做法是建立一個如下的模型：每一個block都有一個entrance，然後path交錯的地方都是可以選擇方向的point。那麼整個地圖上就由這兩類點組成：entrance，intersection。那麼現在要做的就是在這些點之間做連線，選擇一條最優的路徑（比如最短）。這裡尋路的算法是從起點到終點，每一步都選擇離終點 歐幾里得距離 最近的一個點，這樣步步逼近，從而達到尋路的目的。

**Comment by SeddonShen** [comment]
十分感谢！
